<MyGrid>
    GridLayout:
        cols: 1
        size: root.width - 200, root.height - 200
        pos: 100, 100

        GridLayout:
            cols: 2

            Label:
                text: "User name: "

            TextInput:
                multiline: False

            Label:
                text: "Password: "

            TextInput:
                multiline: False
        Button:
            text: "Submit"